Add right text when toggles are enabled in preferences
openfoodfacts/openfoodfacts-androidapp pull request #3552
Opened 2020-10-21 03:14 UTC by sarah541

####  Description

Add right text when toggles are enabled in preferences

#### Related issues

#### Related PRs

#### Screenshots

**Before**
![Screenshot_20201020-181135_OpenFoodFacts](https://user-images.githubusercontent.com/29518411/96668712-c125d100-1329-11eb-94aa-74b57a687f97.jpg)

**After**
![Screenshot_20201020-180929_OpenFoodFacts](https://user-images.githubusercontent.com/29518411/96668723-c7b44880-1329-11eb-8378-7fb295f8c047.jpg)

2020-10-21 13:23 UTC, huzaifaiftikhar requested changes
Add the string "enabled" to `strings.xml` and use that instead of hard coding

2020-10-21 13:43 UTC, huzaifaiftikhar approved these changes

2020-10-21 21:45 UTC, teolemon commented
Some screenshots tests are failing
```
2020-10-21T13:44:03.3032744Z Compiling with JDK Java compiler API.
2020-10-21T13:44:03.3034456Z /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/AbstractScreenshotTest.java:25: error: cannot find symbol
2020-10-21T13:44:03.3036765Z import openfoodfacts.github.scrachx.openfood.features.OFFApplication;
2020-10-21T13:44:03.3037994Z                                                      ^
2020-10-21T13:44:03.3038335Z   symbol:   class OFFApplication
2020-10-21T13:44:03.3039271Z   location: package openfoodfacts.github.scrachx.openfood.features
2020-10-21T13:44:03.3041580Z /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/test/ScreenshotActivityTestRule.java:17: error: cannot find symbol
2020-10-21T13:44:03.3084425Z import openfoodfacts.github.scrachx.openfood.features.OFFApplication;
2020-10-21T13:44:03.3085991Z                                                      ^
2020-10-21T13:44:03.3087594Z   symbol:   class OFFApplication
2020-10-21T13:44:03.3088749Z   location: package openfoodfacts.github.scrachx.openfood.features
2020-10-21T13:44:03.3091535Z /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/TakeScreenshotShowProductsTest.java:18: error: cannot find symbol
2020-10-21T13:44:03.3094169Z import openfoodfacts.github.scrachx.openfood.features.HistoryScanActivity;
2020-10-21T13:44:03.3095840Z                                                      ^
2020-10-21T13:44:03.3096268Z   symbol:   class HistoryScanActivity
2020-10-21T13:44:03.3097340Z   location: package openfoodfacts.github.scrachx.openfood.features
2020-10-21T13:44:03.3100075Z /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/TakeScreenshotShowProductsTest.java:19: error: cannot find symbol
2020-10-21T13:44:03.3102728Z import openfoodfacts.github.scrachx.openfood.features.OFFApplication;
2020-10-21T13:44:03.3104205Z                                                      ^
2020-10-21T13:44:03.3104575Z   symbol:   class OFFApplication
2020-10-21T13:44:03.3105585Z   location: package openfoodfacts.github.scrachx.openfood.features
2020-10-21T13:44:03.3109064Z /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/TakeScreenshotShowProductsTest.java:20: error: package openfoodfacts.github.scrachx.openfood.features.product does not exist
2020-10-21T13:44:03.3112875Z import openfoodfacts.github.scrachx.openfood.features.product.ProductActivity;
2020-10-21T13:44:03.3114536Z                                                              ^
2020-10-21T13:44:03.3116467Z /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/TakeScreenshotShowProductsTest.java:28: error: cannot find symbol
2020-10-21T13:44:03.3118586Z     public ScreenshotActivityTestRule<HistoryScanActivity> activityHistoryRule =
2020-10-21T13:44:03.3119390Z                                       ^
2020-10-21T13:44:03.3119802Z   symbol:   class HistoryScanActivity
2020-10-21T13:44:03.3120556Z   location: class TakeScreenshotShowProductsTest
2020-10-21T13:44:03.3122913Z /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/TakeScreenshotShowProductsTest.java:31: error: cannot find symbol
2020-10-21T13:44:03.3125042Z     public ScreenshotActivityTestRule<ProductActivity> activityShowProductRule =
2020-10-21T13:44:03.3125944Z                                       ^
2020-10-21T13:44:03.3126314Z   symbol:   class ProductActivity
2020-10-21T13:44:03.3127020Z   location: class TakeScreenshotShowProductsTest
2020-10-21T13:44:03.3129424Z /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/TakeScreenshotIncompleteProductsTest.java:14: error: cannot find symbol
2020-10-21T13:44:03.3132170Z import openfoodfacts.github.scrachx.openfood.features.OFFApplication;
2020-10-21T13:44:03.3133392Z                                                      ^
2020-10-21T13:44:03.3133734Z   symbol:   class OFFApplication
2020-10-21T13:44:03.3134673Z   location: package openfoodfacts.github.scrachx.openfood.features
2020-10-21T13:44:03.3137164Z /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/TakeScreenshotIncompleteProductsTest.java:15: error: cannot find symbol
2020-10-21T13:44:03.3140196Z import openfoodfacts.github.scrachx.openfood.features.ProductBrowsingListActivity;
2020-10-21T13:44:03.3141883Z                                                      ^
2020-10-21T13:44:03.3142380Z   symbol:   class ProductBrowsingListActivity
2020-10-21T13:44:03.3143469Z   location: package openfoodfacts.github.scrachx.openfood.features
2020-10-21T13:44:03.3145968Z /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/TakeScreenshotIncompleteProductsTest.java:23: error: cannot find symbol
2020-10-21T13:44:03.3149023Z     public ScreenshotActivityTestRule<ProductBrowsingListActivity> incompleteRule = new ScreenshotActivityTestRule<>(ProductBrowsingListActivity.class, "incompleteProducts",
2020-10-21T13:44:03.3150675Z                                       ^
2020-10-21T13:44:03.3151187Z   symbol:   class ProductBrowsingListActivity
2020-10-21T13:44:03.3152174Z   location: class TakeScreenshotIncompleteProductsTest
2020-10-21T13:44:03.3154371Z /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/AbstractScreenshotTest.java:81: error: cannot find symbol
2020-10-21T13:44:03.3156138Z         changeLocale(parameter, OFFApplication.getInstance());
2020-10-21T13:44:03.3156709Z                                 ^
2020-10-21T13:44:03.3157154Z   symbol:   variable OFFApplication
2020-10-21T13:44:03.3157744Z   location: class AbstractScreenshotTest
2020-10-21T13:44:03.3159824Z /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/test/ScreenshotActivityTestRule.java:70: error: cannot find symbol
2020-10-21T13:44:03.3161865Z                 new PrefManager(OFFApplication.getInstance()).setFirstTimeLaunch(firstTimeLaunched);
2020-10-21T13:44:03.3198964Z                                 ^
2020-10-21T13:44:03.3236497Z   symbol:   variable OFFApplication
2020-10-21T13:44:03.3237188Z   location: class ScreenshotActivityTestRule<T>
2020-10-21T13:44:03.3238154Z   where T is a type-variable:
2020-10-21T13:44:03.3238852Z     T extends Activity declared in class ScreenshotActivityTestRule
2020-10-21T13:44:03.3241122Z /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/TakeScreenshotShowProductsTest.java:29: error: cannot find symbol
2020-10-21T13:44:03.3248505Z         new ScreenshotActivityTestRule<>(HistoryScanActivity.class);
2020-10-21T13:44:03.3249255Z                                          ^
2020-10-21T13:44:03.3249673Z   symbol:   class HistoryScanActivity
2020-10-21T13:44:03.3250428Z   location: class TakeScreenshotShowProductsTest
2020-10-21T13:44:03.3252833Z /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/TakeScreenshotShowProductsTest.java:32: error: cannot find symbol
2020-10-21T13:44:03.3255014Z         new ScreenshotActivityT [...]

2020-10-23 15:37 UTC, VaiTon approved these changes

2020-10-23 15:37 UTC, merged