Added Build Number in settings
openfoodfacts/openfoodfacts-androidapp pull request #3740
Opened 2021-01-15 11:40 UTC by mrudultora

####  Description
Added _versionCode / Build Number_ in Settings ( Preferences Fragment ).

#### Related issues
Fixes #3736 

#### Related PRs
None

#### Screenshots

2021-01-15 23:27 UTC, VaiTon requested changes

2021-01-15 23:27 UTC, VaiTon commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/PreferencesFragment.kt
> +                it.summary = getString(R.string.version_string) + " " + version+" ("+ versionCode + ")"
Please use string template.

2021-01-15 23:27 UTC, VaiTon commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/PreferencesFragment.kt
> +                val versionCode = if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.P){
Please format the file

2021-01-16 08:35 UTC, mrudultora commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/PreferencesFragment.kt
> +                it.summary = getString(R.string.version_string) + " " + version+" ("+ versionCode + ")"
How will I use string template here ?

2021-01-16 17:26 UTC, mrudultora commented
@VaiTon  Are the changes correct ?

2021-01-17 12:17 UTC, VaiTon approved these changes

2021-01-17 12:17 UTC, VaiTon commented
> 
> 
> @VaiTon Are the changes correct ?

See latest commit

2021-01-17 18:11 UTC, merged