Fixed grey food scores displayed for cosmetics
openfoodfacts/openfoodfacts-androidapp pull request #3745
Opened 2021-01-15 21:13 UTC by mrudultora

####  Description
Added a _if_ block to check the build flavor. If the build flavor is  **"off"** then only the food scores are visible. 

#### Related issues
Fixes #3741

#### Related PRs
None

#### Screenshots
![img](https://user-images.githubusercontent.com/65870389/104779093-7a1e6f00-57a4-11eb-990e-ade4011ae5a0.jpg)

2021-01-15 23:20 UTC, VaiTon requested changes

2021-01-15 23:20 UTC, VaiTon commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/adapters/ProductsRecyclerViewAdapter.kt
> +        if(BuildConfig.FLAVOR == "off") {
Use `AppFlavors.isFlavors(AppFlavors.OFF)`

2021-01-16 08:43 UTC, mrudultora commented
@VaiTon Changes done accordingly !

2021-01-16 10:02 UTC, VaiTon approved these changes

2021-01-16 10:02 UTC, merged