Fixed ISE when fragment is not attached to activity
openfoodfacts/openfoodfacts-androidapp pull request #3768
Opened 2021-01-22 17:51 UTC by mrudultora

####  Description
Used `isAdded()` to check whether the fragment is attached to an activity.

#### Related issues
Fixes - #3743 

#### Related PRs
None

#### Screenshots

2021-01-23 16:45 UTC, VaiTon requested changes

2021-01-23 16:45 UTC, VaiTon commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/ingredients/IngredientsProductFragment.kt
> +        if (isAdded) {
Could you invert this `if` and place it before `ingredientExtracted = true`?

2021-01-23 16:53 UTC, mrudultora commented
@VaiTon  Changes Done !

2021-01-24 10:06 UTC, VaiTon requested changes

2021-01-24 10:06 UTC, VaiTon commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/ingredients/IngredientsProductFragment.kt
> +        if (isAdded) {
```suggestion
        if (!isAdded) return
```

2021-01-24 10:06 UTC, VaiTon commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/ingredients/IngredientsProductFragment.kt
>          }
```suggestion
```

2021-01-29 16:53 UTC, merged