fix: don't replace fragment on another fragment if they are the same
openfoodfacts/openfoodfacts-androidapp pull request #3835
Opened 2021-02-16 08:49 UTC by naivekook

####  Description
when user clicks on "Home" button twice we did a replacement of current fragment on new instance of this fragment and do extra calls to the server

#### Related issues
Fixes #3465
https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3465

2021-02-17 08:52 UTC, naivekook commented
@VaiTon please take a look

2021-02-17 18:43 UTC, VaiTon commented
I don't really like this implementation using tag string. Can't we compare using `is`, for example? Is there a way to get the actual displayed fragment?

2021-02-18 07:33 UTC, naivekook commented
> I don't really like this implementation using tag string.
Can I ask you why?

fragment manager doesn't have convenient mechanism to retrieve current fragment, by combining `findFragmentByTag` and `fragment.isVisible` we can understand this

looks like we use `replace` everywhere without backstack so we have only one fragment attached, in this case I can do next thing and it will work too
```
with((currentActivity as FragmentActivity).supportFragmentManager) {
                        val fragment = fragments.lastOrNull()
                        if (fragment == null || fragment !is HomeFragment) {
                            commit {
                                replace(R.id.fragment_container, HomeFragment.newInstance(), HomeFragment.TAG)
                                addToBackStack(null)
                            }
                        }
                    }
```

2021-02-18 22:42 UTC, VaiTon commented
> 
> 
> > I don't really like this implementation using tag string.
> 
> Can I ask you why?

Just because it's a useless var if we can check the type as you showed IMHO. 

About your second solution, if you could test it and see if it works it would be awesome!

2021-02-20 10:21 UTC, naivekook commented
@VaiTon hey check updated version please
I've been tested it on emulator and it works

2021-02-27 18:00 UTC, VaiTon requested changes

2021-02-27 18:00 UTC, VaiTon commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/MainActivity.kt
> +        with(supportFragmentManager) {
Really hate saying this but i think `let` would be more clear when calling methods. Could you replace `with` with `let`?

2021-02-27 18:00 UTC, VaiTon commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/MainActivity.kt
> +            if (currentFragment == null || currentFragment::class.java != fragment::class.java) {
Why don't we use `currentFragment !is fragment::class`?

2021-02-27 18:00 UTC, VaiTon commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/searchbycode/SearchByCodeFragment.kt
> +        fun newInstance(barcode: String? = null) = SearchByCodeFragment().apply {
Why this? We cannot search by code without any code.

2021-02-27 18:00 UTC, VaiTon commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/listeners/CommonBottomListener.kt
> +                    with((currentActivity as FragmentActivity).supportFragmentManager) {
Could we extract a method out of this?

2021-02-27 20:19 UTC, naivekook commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/searchbycode/SearchByCodeFragment.kt
> +        fun newInstance(barcode: String? = null) = SearchByCodeFragment().apply {
sorry I don't get you

actually I see that we dont have any usages of this method so we can remove it safely I guess

2021-02-27 20:22 UTC, naivekook commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/MainActivity.kt
> +            if (currentFragment == null || currentFragment::class.java != fragment::class.java) {
your variant isn't working

2021-02-27 20:25 UTC, naivekook commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/MainActivity.kt
> +        with(supportFragmentManager) {
well this is more "style dispute", removed `with`

2021-02-27 20:26 UTC, naivekook commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/listeners/CommonBottomListener.kt
> +                    with((currentActivity as FragmentActivity).supportFragmentManager) {
sure, done

2021-02-27 20:27 UTC, naivekook commented
ptal @VaiTon

2021-03-02 20:41 UTC, VaiTon approved these changes

2021-03-02 20:41 UTC, merged

2021-03-02 20:42 UTC, VaiTon commented
Thanks! 🎉