Made the day and night strings untranslatable
openfoodfacts/openfoodfacts-androidapp pull request #3876
Opened 2021-03-07 18:44 UTC by mrudultora

####  Description
Made `@string/day` and `@string/night` untranslatable.

#### Related issues
Fixes #3837

2021-03-07 19:23 UTC, teolemon approved these changes

2021-03-07 19:25 UTC, teolemon requested changes
@mrudultora I was thinking of that  
  <!-- Application theme settings -->
    <string-array name="application_theme_entries">
        <item>@string/follow_system</item>
        <item>@string/day</item>
        <item>@string/night</item>
    </string-array>

2021-03-07 19:28 UTC, mrudultora commented
Making the string array untranslatable?

2021-03-11 11:19 UTC, teolemon commented on app/src/main/res/values/strings.xml
> +    <string name="night" translatable="false">Night</string>
```suggestion
    <string name="day">Day</string>
    <string name="night">Night</string>
```

2021-03-11 11:20 UTC, teolemon approved these changes

2021-03-11 11:20 UTC, merged