Remove DataBinding from project
openfoodfacts/openfoodfacts-androidapp pull request #4153
Opened 2021-08-11 05:33 UTC by naivekook

####  Description
I took the initiative of making this change without final resolution in the slack thread https://openfoodfacts.slack.com/archives/C02L15QLA/p1628503633025900.

As I said in the slack all our new code was written without data-binding approach, so looks like we depend on this library only for legacy code. By removing this library we can use more clean XML files and decrease build time from 2.29min to 1.26min(!!). I didn't make any measuring of apk file but think it is decreased too.

This PR removes data-binding from the project and introduces view-binding instead. 
There are a lot of changes inside XML files, but mostly this is formatting (because of removing layout and data tags) and adding `tools:ignore="ContentDescription"` to ImageView to prevent lint from warning.
Also, some fragments were fixed because they used to use data-binding before.

#### Related links
With data binding
https://scans.gradle.com/s/gv47vexa7beck/performance/build

Without data binding
https://scans.gradle.com/s/ggg6psw3cdnca/performance/build

#### Screenshots
With data binding
<img width="678" alt="Screenshot 2021-08-11 at 08 20 26" src="https://user-images.githubusercontent.com/1501831/128973759-7784f3ba-cbdb-4b48-b1be-2bf39bdf239c.png">

Without data binding
<img width="669" alt="Screenshot 2021-08-11 at 08 20 34" src="https://user-images.githubusercontent.com/1501831/128973765-c642d484-3a68-49f9-a2ee-457bfdb1528c.png">

2021-08-11 15:22 UTC, VaiTon commented
@naivekook I really don't know. 

Data binding is used in some code which is not legacy and I don't know if we should remove it completely. The reduction in the compilation time is really good but it's really useful to put some logic code in the xml file instead of cluttering up the Activity/Fragment.

Also, with the introduction of Composable views, which I would like to introduce to this project when we remove the API requirement for older version, will completely change how we work with views.

@teolemon any view?

2021-08-11 15:25 UTC, VaiTon requested changes
Partial review, will complete later

2021-08-11 15:25 UTC, VaiTon commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/analyticsusage/AnalyticsUsageDialogFragment.kt
> +            .apply()
```suggestion
            .edit { putBoolean(getString(R.string.pref_analytics_reporting_key), value) }
```

And import the required extension.

2021-08-11 15:33 UTC, VaiTon commented
@naivekook also, it doesn't compile

2021-08-11 16:12 UTC, naivekook commented
@teolemon sure it is always a trade-off
My opinion here is not to mix approaches inside the code. For example, you have a bug, you go to Fragment and try to find and fix it, but looks like all works fine, but suddenly, you understand, that some variable is injected into XML directly by data-binding and it causes this bug.
And how many fragments do we have? about 20? and only 3-4 uses the data-binding, so no such big price for improving the build time and code sustainability
By the way, you don't use both java and kotlin for new code right? :)

> with the introduction of Composable views
wow that's awesome! love the Jetpack Compose
but with introducing the compose this in another +1 to get rid of data-binding ;)

> also, it doesn't compile
I tested only offFdroidDebug variant, will fix all other variants and tests if we will decide to ship this PR


anyway I'm not pushing much, just want to bring another point of view and possible improvement :)

2021-08-11 17:29 UTC, VaiTon commented
@naivekook ok, you convinced me. Let's do this :)

2021-08-12 08:36 UTC, teolemon commented
I was about to say that I had no opinion on the matter ;-)

2021-08-13 14:50 UTC, naivekook commented
@VaiTon review it again, please
I tested FDroid and Playstore versions on the device and looks like it is all fine

2021-08-13 14:52 UTC, VaiTon approved these changes

2021-08-14 16:17 UTC, teolemon commented
@VaiTon @naivekook safe to merge ?

2021-08-14 16:23 UTC, naivekook commented
@teolemon merge it after release please

2021-08-14 16:25 UTC, teolemon commented
ok, noted.

2021-09-06 10:00 UTC, naivekook commented
I'm working on MacBook air right now and the build time is awful, can we consider merging it right now?

2021-09-06 14:21 UTC, VaiTon commented
@teolemon ?

2021-09-06 15:13 UTC, merged