Try to fix the Lint Error about WorkManagerInitializer
openfoodfacts/openfoodfacts-androidapp pull request #4452
Opened 2022-01-29 13:31 UTC by teolemon

Try to fix the Lint Error about WorkManagerInitializer

2022-01-29 14:01 UTC, teolemon commented
Error: Missing registered class: Class referenced in the manifest, `androidx.Startup`, was not found in the project or the libraries

2022-03-06 11:00 UTC, R4md4c requested changes

2022-03-06 11:00 UTC, R4md4c commented on app/src/main/AndroidManifest.xml
> +            android:name="androidx.startup"
To disable workmanager startup, from the android [documentation](https://developer.android.com/topic/libraries/architecture/workmanager/advanced/custom-configuration), I believe it should be:

```
 <provider
    android:name="androidx.startup.InitializationProvider"
    android:authorities="${applicationId}.androidx-startup"
    android:exported="false"
    tools:node="merge">
    <!-- If you are using androidx.startup to initialize other components -->
    <meta-data
        android:name="androidx.work.WorkManagerInitializer"
        android:value="androidx.startup"
        tools:node="remove" />
 </provider>
```

2022-03-22 11:37 UTC, teolemon commented
fixed by @g123k

2022-03-22 11:37 UTC, closed without merging