fix: When nutriscore is not (yet) computed, hide the "Learn more" button
openfoodfacts/openfoodfacts-androidapp pull request #4657
Opened 2022-04-09 06:56 UTC by g123k

Will fix #4620

2022-04-09 11:28 UTC, VaiTon requested changes

2022-04-09 11:28 UTC, VaiTon commented on app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/nutrition/NutritionProductFragment.kt
> +        binding.nutriscoreLink.visibility = if (product.nutritionGradeFr != null) VISIBLE else GONE
```suggestion
        binding.nutriscoreLink.isVisible = product.nutritionGradeFr != null
```
From [core-ktx](https://android.github.io/android-ktx/core-ktx/androidx.view/android.view.-view/is-visible.html)

2022-04-09 11:44 UTC, VaiTon approved these changes

2022-04-14 14:03 UTC, g123k commented
@teolemon & @VaiTon If it's ok for both, could we merge this?

2022-04-15 17:41 UTC, merged