style : Added new logo in README.md
openfoodfacts/openfoodfacts-androidapp pull request #4915
Opened 2023-02-14 02:56 UTC by dmdbilal

####  Description

Added new logo in README.md
#### Related issues

#4832

2023-02-18 14:24 UTC, VaiTon commented
We should still use the logo from the static website. Another alternative is to upload the logo to github. With this PR I don't know where is that link pointing

2023-02-18 19:55 UTC, pratyaksh1610 requested changes
Also, please add a before and after image for easier review and for maintaining history.
Also the test fails. PTAL.

2023-02-20 04:54 UTC, dmdbilal commented
@VaiTon I've downloaded the logos from the drive that was provided in the issue #4832. If that is not, then where can i get the logos ?

2023-02-22 11:11 UTC, VaiTon commented
@dmdbilal you should do as this does: https://raw.githubusercontent.com/openfoodfacts/.github/main/profile/README.md

2023-02-27 13:31 UTC, dmdbilal commented
@VaiTon Can you check now ?

2025-07-07 11:32 UTC, closed without merging